// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-mobile-comparison/OptA.tsx": () => import("../components/mockups/home-mobile-comparison/OptA.tsx"),
  "./components/mockups/home-mobile-comparison/OptB.tsx": () => import("../components/mockups/home-mobile-comparison/OptB.tsx")
};
